fix for TypeError: a bytes-like object is required, not 'str'
File "/home/maciek/work/github/rtclite3/rtclite/std/ietf/rfc3261.py", line 767, in createClient
    t.start()
  File "/home/maciek/work/github/rtclite3/rtclite/std/ietf/rfc3261.py", line 840, in start
    self.stack.send(self.request, self.remote, self.transport)
  File "/home/maciek/work/github/rtclite3/rtclite/std/ietf/rfc3261.py", line 512, in send
    self.app.send(str(data), dest, stack=self)
  File "/home/maciek/work/github/rtclite3/rtclite/app/sip/caller.py", line 369, in send
    if stack.transport.type == Stacks.UDP: stack.sock.sendto(data, addr)
  File "/home/maciek/work/github/rtclite3/venv/lib/python3.10/site-packages/gevent/_socketcommon.py", line 703, in sendto
    return self._sock.sendto(*args)
TypeError: a bytes-like object is required, not 'str'